c1f10 = Checkbutton(frm10, text = "Arrendamiento o compra de predios", onvalue = 1, offvalue = 0, variable = f10c1, background = 'white', justify = 'left')
c1f10.place(x = 50, y = 80)
c2f10 = Checkbutton(frm10, text = "Elaboración de acta de vecindad", onvalue = 1, offvalue = 0, variable = f10c2, background = 'white', justify = 'left')
c2f10.place(x = 50, y = 110)
c3f10 = Checkbutton(frm10, text = "Elaboración de acta de entorno", onvalue = 1, offvalue = 0, variable = f10c3, background = 'white', justify = 'left')
c3f10.place(x = 50, y = 140)
c4f10 = Checkbutton(frm10, text = "Pago de servidumbres", onvalue = 1, offvalue = 0, variable = f10c4, background = 'white', justify = 'left')
c4f10.place(x = 50, y = 170)
c5f10 = Checkbutton(frm10, text = "Reasentamiento de familias", onvalue = 1, offvalue = 0, variable = f10c5, background = 'white', justify = 'left')
c5f10.place(x = 50, y = 200)
c6f10 = Checkbutton(frm10, text = "Reconstrucción de andén en concreto con acabado vitrificado antideslizante, arenón chino, espesor de 10cm, incluye piedra entresuelo e=0,15m, arenilla compactada e=0,50 m, juntas y acabados", onvalue = 1, offvalue = 0, variable = f10c6, background = 'white', justify = 'left')
c6f10.place(x = 50, y = 230)
c7f10 = Checkbutton(frm10, text = "Reconstrucción de andén en granito", onvalue = 1, offvalue = 0, variable = f10c7, background = 'white', justify = 'left')
c7f10.place(x = 50, y = 260)
c8f10 = Checkbutton(frm10, text = "Reparación de daños en acometidas y/o redes secundarias de acueducto", onvalue = 1, offvalue = 0, variable = f10c8, background = 'white', justify = 'left')
c8f10.place(x = 50, y = 290)
c9f10 = Checkbutton(frm10, text = "Suministro, transporte y colocación de almancenamiento provisional, por duración de las obras en el tanque de almacenamiento, incluye obra hidráulica, obras ", onvalue = 1, offvalue = 0, variable = f10c9, background = 'white', justify = 'left')
c9f10.place(x = 50, y = 320)
c10f10 = Checkbutton(frm10, text = "Atención médica", onvalue = 1, offvalue = 0, variable = f10c10, background = 'white', justify = 'left')
c10f10.place(x = 50, y = 350)

#checkbuttons frm11
c1f11 = Checkbutton(frm11, text="Buzón de sugerencias en acrílico de 0,30 m * 0,30 m * 0,30 m (según manual de comunicaciones)",onvalue = 1, offvalue = 0,variable = f11c1 ,background = 'white',justify = 'left')
c1f11.place(x = 50, y = 80)
c2f11 = Checkbutton(frm11, text="Cartelera informativa de 1,20 m * 0,80 m en madera con fondo de corcho (según manual de comunicaciones)",onvalue = 1, offvalue = 0,variable = f11c2 ,background = 'white',justify = 'left')
c2f11.place(x = 50, y = 110)
c3f11 = Checkbutton(frm11, text="Centro de atención móvil",onvalue = 1, offvalue = 0,variable = f11c3 ,background = 'white',justify = 'left')
c3f11.place(x = 50, y = 140)
c4f11 = Checkbutton(frm11, text="Cuña radial informativa",onvalue = 1, offvalue = 0,variable = f11c4 ,background = 'white',justify = 'left')
c4f11.place(x = 50, y = 170)
c5f11 = Checkbutton(frm11, text="Elaboración de testimonios",onvalue = 1, offvalue = 0,variable = f11c5 ,background = 'white',justify = 'left')
c5f11.place(x = 50, y = 200)
c6f11 = Checkbutton(frm11, text="Gestión informativa en redes sociales (diseñador wed + impresos)",onvalue = 1, offvalue = 0,variable = f11c6 ,background = 'white',justify = 'left')
c6f11.place(x = 50, y = 230)
c7f11 = Checkbutton(frm11, text="Logística reuniones con la comunidad (alquiler video beam, refrigerios para 50 personas)",onvalue = 1, offvalue = 0,variable = f11c7 ,background = 'white',justify = 'left')
c7f11.place(x = 50, y = 260)
c8f11 = Checkbutton(frm11, text="Logística reuniones con la comunidad (alquiler video beam, refrigerios para 100 personas)",onvalue = 1, offvalue = 0,variable = f11c8 ,background = 'white',justify = 'left')
c8f11.place(x = 50, y = 290)
c9f11 = Checkbutton(frm11, text="Pasacalles 7 m * 0,7 m en lona (según manual de comunicaciones)",onvalue = 1, offvalue = 0,variable = f11c9 ,background = 'white',justify = 'left')
c9f11.place(x = 50, y = 320)
c10f11 = Checkbutton(frm11, text="Pendón de 3.00 mt x 2.00 mts, 4x0 con hojaletes, diseños a definir",onvalue = 1, offvalue = 0,variable = f11c10,background = 'white',justify = 'left')
c10f11.place(x = 50, y = 350)
c11f11 = Checkbutton(frm11, text="Plotter adhesivo 70x23 cm, 4x0, full color Ref. Cartelera",onvalue = 1, offvalue = 0,variable = f11c11,background = 'white',justify = 'left')
c11f11.place(x = 50, y = 380)
c12f11 = Checkbutton(frm11, text="Plotter adhesivo 70x23 cm, 4x0, full color Ref. Buzón",onvalue = 1, offvalue = 0,variable = f11c12,background = 'white',justify = 'left')
c12f11.place(x = 50, y = 410)
c13f11 = Checkbutton(frm11, text="Stiker logo Antioquia la mas educada 7 x 7",onvalue = 1, offvalue = 0,variable = f11c13,background = 'white',justify = 'left')
c13f11.place(x = 50, y = 440)
c14f11 = Checkbutton(frm11, text="Valla (6mx4m). Incluye estructura metálica para fijación y soporte",onvalue = 1, offvalue = 0,variable = f11c14,background = 'white',justify = 'left')
c14f11.place(x = 50, y = 470)
c15f11 = Checkbutton(frm11, text="Volantes según oficina de comunicaciones de la Gobernación (2.000 unidades x Municipio)",onvalue = 1, offvalue = 0,variable = f11c15,background = 'white',justify = 'left')
c15f11.place(x = 50, y = 500)
c16f11 = Checkbutton(frm11, text="Volantes según oficina de comunicaciones de la Gobernación (2.000 unidades x Municipio)",onvalue = 1, offvalue = 0,variable = f11c16,background = 'white',justify = 'left')
c16f11.place(x = 50, y = 530)
c17f11 = Checkbutton(frm11, text="Distribución de cartillas o manuales",onvalue = 1, offvalue = 0,variable = f11c17,background = 'white',justify = 'left')
c17f11.place(x = 50, y = 560)
c18f11 = Checkbutton(frm11, text="Prospección arqueológica",onvalue = 1, offvalue = 0,variable = f11c18,background = 'white',justify = 'left')
c18f11.place(x = 50, y = 590)

#checkbuttons frm12

c1f12 = Checkbutton(frm12, text = "Construcción de acopios en madera para cemento, acero, pétreos, productos químicos, residuos sólidos",onvalue = 1, offvalue = 0, variable = f12c1 , background = 'white', justify = 'left')
c1f12.place(x = 50,y = 80)
c2f12 = Checkbutton(frm12, text = 'Construcción de polvorín en concreto de 21 MPa de resistencia, de 1,40m x 1,40m por 2,60m de alto con losa de contrapiso de 20cm, muros y losa de cubierta de espesor 10 cm, con puerta metálica de 2,10m x 0,8m con chapilla de madera en su interior, sistema de ventilación compuesto por dos codos de PVC 4" para ventilación en la losa de cubierta, Incluye acero de refuerzo y todos los demás elementos necesarios para su correcta construcción, según diseño.',onvalue = 1, offvalue = 0, variable = f12c2 , background = 'white', justify = 'left')
c2f12.place(x = 50,y = 110)
c3f12 = Checkbutton(frm12, text = "Instalación de cerramiento provisional en tela verde con una altura de 2,1 m. Incluye suministro, transporte e instalación de la tela, estructura en taco de madera común, concreto de 14 MPa, según diseño de mezclas aprobado por la interventoría para fijación de estructura en madera común, excavación manual en cualquier material, cargue, transporte y botada de material y todos los demás elementos necesarios para su correcta instalación.",onvalue = 1, offvalue = 0, variable = f12c3 , background = 'white', justify = 'left')
c3f12.place(x = 50,y = 140)
c4f12 = Checkbutton(frm12, text = "Instalación de cerramiento en teja ondulada de zinc calibre 35e:0,20mm, con altura de 2,20 metros. Incluye suministro, transporte e instalación de la teja, estructura en madera cada metros, larguero horizontal en la parte superior, concreto de 17,5 Mpa para fijación de estructura en madera común, vientos en madera cada 3m, excavación manual en cualquier materiales, cargue, transporte y botada de material.",onvalue = 1, offvalue = 0, variable = f12c4 , background = 'white', justify = 'left')
c4f12.place(x = 50,y = 170)
c5f12 = Checkbutton(frm12, text = "Malla polisombra, para proteger de la contaminación por polvo (ancho de 3,0m referencia 70%)",onvalue = 1, offvalue = 0, variable = f12c5 , background = 'white', justify = 'left')
c5f12.place(x = 50,y = 200)
c6f12 = Checkbutton(frm12, text = "Malla polisombra, para proteger de la contaminación por polvo (ancho de 2,1m de ancho)",onvalue = 1, offvalue = 0, variable = f12c6 , background = 'white', justify = 'left')
c6f12.place(x = 50,y = 230)
c7f12 = Checkbutton(frm12, text = "Suministro, transporte e instalación de tanque de almacenamiento de combustible para planta eléctrica en poliéster reforzado con fibra de vidrio, volumen de 1m3 (incluye base de tanque PRFV)",onvalue = 1, offvalue = 0, variable = f12c7 , background = 'white', justify = 'left')
c7f12.place(x = 50,y = 260)
c8f12 = Checkbutton(frm12, text = 'Suministro, transporte e instalación de cubierta tipo invernadero, provisional en plástico agrícola. Incluye estructura madera inmunizada, plástico TRATADO UV para invernadero o equivalente con un calibre de 7, colocado a una altura entre 4 y 6 m, cables de súper GX de 3/16" y 1/4", guarda cabos, tensores, grilletes, cinta, alambre No 13, excavación manual postes en madera inmunizada y vientos en cualquier material y los respectivos muertos para cada viento. Incluye el posterior desmonte de los elementos y botada del material, así́ como todos los demás elementos necesarios para su correcta instalación. La instalación se debe realizar con personal certificado con su respectiva dotación y equipos para trabajo en alturas. Esta actividad se realizará con previa autorización de la interventoría en caso de requerirse.',onvalue = 1, offvalue = 0, variable = f12c8 , background = 'white', justify = 'left')
c8f12.place(x = 50,y = 290)
c9f12 = Checkbutton(frm12, text = 'Otros - adecuación de maquinaria, equipos y planta industrial',onvalue = 1, offvalue = 0, variable = f12c9 , background = 'white', justify = 'left')
c9f12.place(x = 50,y = 320)
c10f12 = Checkbutton(frm12, text = "Adquisición de kit de atención de derrames",onvalue = 1, offvalue = 0, variable = f12c10, background = 'white', justify = 'left')
c10f12.place(x = 50,y = 350)
